### PR TITLE
add link after the simulation is completed

### PR DESCRIPTION
**Pull request by xyang0089**
image

### CODE REVIEW

**Review by dallasbrittany — CHANGES_REQUESTED** [review]
This does work for me, but I am wondering if we should change the link to `https://www.capitalone.com/learn-grow/money-management/` to match our changes in `Financial-App/src/components/simulation/Additional_Resources.tsx`?

**Comment by xyang0089** [comment]
> `Financial-App/src/components/simulation/Additional_Resources.tsx`?

@dallasbrittany  because this page happens after the additional resources. Does it really make sense to have the same link again?

**Comment by dallasbrittany** [comment]
> > `Financial-App/src/components/simulation/Additional_Resources.tsx`?
> 
> 
> 
> @dallasbrittany  because this page happens after the additional resources. Does it really make sense to have the same link again?

Well I think we were just trying to make sure they could get back to the same link after the timer ended. I guess it is a bit misleading though to say additional resources if we already provided this link. It would be even better if we had more resources than just one to share. They shouldn't all be Capital One links either in my opinion. But the reason I commented on this PR here is because of the point raised in our meeting about how linking to business resources might not be very useful for students.

**Comment by xyang0089** [comment]
> > > `Financial-App/src/components/simulation/Additional_Resources.tsx`?
> > 
> > 
> > @dallasbrittany  because this page happens after the additional resources. Does it really make sense to have the same link again?
> 
> Well I think we were just trying to make sure they could get back to the same link after the timer ended. I guess it is a bit misleading though to say additional resources if we already provided this link. It would be even better if we had more resources than just one to share. They shouldn't all be Capital One links either in my opinion. But the reason I commented on this PR here is because of the point raised in our meeting about how linking to business resources might not be very useful for students.

This is just what links they had in there already. Not sure why they were providing capital one links. I am fine with either way. If you want, I can just replace it with the link in the additional resources.

**Review by dallasbrittany — APPROVED** [review]

**Pull request merged**
