### PR TITLE
add modal to replace native window popup

### PR DESCRIPTION
**Pull request by xyang0089**
I have a hard to get the UI to the pretest stage so couldn't test this 😢

### CODE REVIEW

**Review by dallasbrittany — CHANGES_REQUESTED** [review]
I was able to test it out, but I think maybe we should change the colors to fit with the app's colors. You can test it if you make a new account (with the live app, not the local app) and add yourself to the class. If you need to use an existing email, just add to it with a plus sign. Like if you used test@whatever.com originally, use test+test1@whatever.com. Here's what it looks like. It does work. I tested both the yes and no options. (I'll need to make a new account to test again. 😅 )

Screenshot 2024-11-13 at 19 13 44

**Comment by xyang0089** [comment]
> I was able to test it out, but I think maybe we should change the colors to fit with the app's colors. You can test it if you make a new account (with the live app, not the local app) and add yourself to the class. If you need to use an existing email, just add to it with a plus sign. Like if you used [test@whatever.com](mailto:test@whatever.com) originally, use [test+test1@whatever.com](mailto:test+test1@whatever.com). Here's what it looks like. It does work. I tested both the yes and no options. (I'll need to make a new account to test again. 😅 )
> 
> Screenshot 2024-11-13 at 19 13 44

Do you mind providing me the link to their live app? I couldn't find it anymore 😢

**Comment by xyang0089** [comment]
image

**Review by dallasbrittany — APPROVED** [review]
Thanks!! This works for me too.
Screenshot 2024-11-18 at 22 03 14

**Comment by dallasbrittany** [comment]
So we have a reference for what it looked like before:
Screenshot 2024-11-18 at 22 08 34

**Pull request merged**
